#pragma once

#define CAPS_LOCK_LED_INDEX  70
#define DRIVER_LED_TOTAL 100
#ifdef OPENRGB_ENABLE
    #define OPENRGB_DIRECT_MODE_USE_UNIVERSAL_BRIGHTNESS
#endif

#define OPENRGB_GET_PROTOCOL_VERSION
#define OPENRGB_GET_QMK_VERSION
#define OPENRGB_GET_DEVICE_INFO
#define OPENRGB_GET_MODE_INFO
#define OPENRGB_GET_LED_INFO
#define OPENRGB_GET_ENABLED_MODES

#define OPENRGB_SET_MODE
#define OPENRGB_DIRECT_MODE_SET_SINGLE_LED
#define OPENRGB_DIRECT_MODE_SET_LEDS

#define OPENRGB_FAILURE
#define OPENRGB_SUCCESS
#define OPENRGB_END_OF_MESSAGE